# A lot of this is the *absolute minimum* possible to use matter, it was never intended to run
# on a device with that little RAM

CONFIG_NETWORKING=y
CONFIG_NET_L2_OPENTHREAD=y
CONFIG_OPENTHREAD_THREAD_VERSION_1_2=y
CONFIG_OPENTHREAD_SLAAC=y
CONFIG_OPENTHREAD_MANUAL_START=y
CONFIG_OPENTHREAD_DEFAULT_TX_POWER=13

# Logging
CONFIG_LOG=n
# CONFIG_LOG_MAX_LEVEL=3
# CONFIG_MATTER_LOG_LEVEL=1
# CONFIG_LOG_MODE_MINIMAL=y

# Use NVS as settings backend
CONFIG_NVS=y
CONFIG_NVS_LOOKUP_CACHE=y
CONFIG_NVS_LOOKUP_CACHE_SIZE=128
CONFIG_NVS_INIT_BAD_MEMORY_REGION=y

# Kernel options
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_INIT_STACKS=y

# Control
CONFIG_LED=y
CONFIG_LED_PWM=y

# Safety
CONFIG_WATCHDOG=y
CONFIG_REBOOT=y

# BLE for provisioning
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="BL702 Bulb"
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y
CONFIG_BT_GATT_DYNAMIC_DB=y
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_DEVICE_NAME_GATT_WRITABLE=n
CONFIG_BT_BUF_ACL_TX_COUNT=2
CONFIG_BT_BUF_EVT_RX_COUNT=4
CONFIG_BT_BUF_ACL_RX_SIZE=100
CONFIG_BT_BUF_ACL_TX_SIZE=100
CONFIG_BT_L2CAP_TX_MTU=100

# Matter
CONFIG_CHIP=y
CONFIG_CHIP_PROJECT_CONFIG="include/CHIPProjectConfig.h"
CONFIG_CHIP_DEVICE_PRODUCT_ID=32773
CONFIG_CHIP_ENABLE_PAIRING_AUTOSTART=y
CONFIG_CHIP_FACTORY_DATA=n
CONFIG_CHIP_CRYPTO_PSA=y
CONFIG_CHIP_BLE_ADVERTISING_DURATION=15
CONFIG_CHIP_MALLOC_SYS_HEAP=y
CONFIG_CHIP_DEVICE_PRODUCT_NAME="BL702 Bulb"
CONFIG_CHIP_DEVICE_VENDOR_NAME="Zephyr Community"
# It is a RGBW dimmable Lamp with 5 PWM channels
CONFIG_CHIP_DEVICE_TYPE=269
CONFIG_CHIP_DEVICE_SOFTWARE_VERSION_STRING="Yes, there is software"
CONFIG_CHIP_DEVICE_HARDWARE_VERSION_STRING="Yes, there is hardware"
CONFIG_CHIP_DEVICE_SOFTWARE_VERSION=1
CONFIG_CHIP_DEVICE_HARDWARE_VERSION=1
CONFIG_CHIP_EXAMPLE_DEVICE_INFO_PROVIDER=n

CONFIG_POSIX_AEP_CHOICE_NONE=y

# Don't starve BLE by starting thread after a factory reset
CONFIG_CHIP_FACTORY_RESET_ERASE_SETTINGS=y

CONFIG_NET_IF_MCAST_IPV6_ADDR_COUNT=8
CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT=6
CONFIG_NET_PKT_RX_COUNT=6
CONFIG_NET_PKT_TX_COUNT=4
CONFIG_NET_BUF_RX_COUNT=16
CONFIG_NET_BUF_TX_COUNT=12

CONFIG_STD_CPP17=y
CONFIG_BT_HOST_CRYPTO=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
CONFIG_MAIN_STACK_SIZE=2944
# CONFIG_SHELL_STACK_SIZE=3072
CONFIG_OPENTHREAD_THREAD_STACK_SIZE=5120

CONFIG_THREAD_LOCAL_STORAGE=y
# CONFIG_ASSERT=y

CONFIG_SHELL=n
#CONFIG_SHELL_MINIMAL=y
CONFIG_CHIP_LIB_SHELL=n
CONFIG_OPENTHREAD_SHELL=n

CONFIG_MBEDTLS_PSA_KEY_SLOT_COUNT=32
CONFIG_MBEDTLS_ENTROPY_C=y
CONFIG_MBEDTLS_PSA_DRIVER_GET_ENTROPY=y
CONFIG_MBEDTLS_PSA_STATIC_KEY_SLOTS=n
CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=1560
CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=1560
CONFIG_MBEDTLS_ENABLE_HEAP=n

# CONFIG_COMMON_LIBC_MALLOC=y
# CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=16384

# Save ram
CONFIG_CHIP_OPENTHREAD_FTD=n
CONFIG_OPENTHREAD_MTD=y
CONFIG_CHIP_ENABLE_DNS_CLIENT=n
CONFIG_OPENTHREAD_DNS_CLIENT=n
CONFIG_OPENTHREAD_NUM_MESSAGE_BUFFERS=48
CONFIG_OPENTHREAD_MAX_CHILDREN=1
CONFIG_OPENTHREAD_MAX_IP_ADDR_PER_CHILD=4
CONFIG_OPENTHREAD_TMF_ADDRESS_CACHE_ENTRIES=0
CONFIG_MAX_EVENT_QUEUE_SIZE=40
CONFIG_BT_GATT_CACHING=n
CONFIG_BT_LONG_WQ=n
CONFIG_POSIX_THREAD_THREADS_MAX=1
CONFIG_MAX_PTHREAD_MUTEX_COUNT=1
CONFIG_MAX_PTHREAD_COND_COUNT=1
CONFIG_MAX_PTHREAD_BARRIER_COUNT=1
CONFIG_NET_TC_RX_COUNT=0

CONFIG_NET_IPV6_NBR_CACHE=n
CONFIG_NET_IPV6_ND=n
CONFIG_NET_IPV6_DAD=n
CONFIG_NET_IPV6_MLD=n

CONFIG_BFLB_SHIM_HEAP_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=6144
CONFIG_HEAP_MEM_POOL_IGNORE_MIN=y
CONFIG_CBPRINTF_FP_SUPPORT=n
CONFIG_PICOLIBC_IO_FLOAT=n

# Slightly dangerous but only a possible (rare) problem for setup
CONFIG_BT_TX_PROCESSOR_THREAD=n

CONFIG_IDLE_STACK_SIZE=320
